version: '3'
services:
 web:
  image: nginx:latest
  environment:
    COMPOSE_CONVERT_WINDOWS_PATHS: 1
  ports:
   - "8080:80"
  volumes:
   - C:\Users\Feighen\workspace:/workspace:rw
   - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
   - php

 php:
  image: php:7-fpm
  volumes:
   - C:\Users\Feighen\workspace:/workspace:rw

 mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BTHFHYVrdtyh674d}  